export const LOG_IN_PENDING = 'LOG_IN_PENDING';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
export const IS_EMAIL_AVAILABLE =  'IS_EMAIL_AVAILABLE';