export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPLOAD_PROFILE = 'UPLOAD_PROFILE';