export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPLOAD_PROFILE = 'UPLOAD_PROFILE';
export const LOAD_LISTINGS = 'LOAD_LISTINGS';
export const SET_LISTINGS = 'SET_LISTINGS';
export const CLEAR_LISTINGS = 'CLEAR_LISTINGS';